spring:
  thymeleaf:
    cache: false # 개발 중에는 캐시를 비활성화하면 템플릿 변경사항이 바로 반영됩니다.
    prefix: classpath:/templates/ # Thymeleaf 템플릿 파일의 위치
    suffix: .html # Thymeleaf 템플릿 파일의 확장자
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create # 또는 update, create-drop 등
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
